name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git config --global core.editor "vim"
      - run: hub pull-request -m "Second Commit2" --reviewer "SujayAtYash" --base master --head tea -l "Please Review" 
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
      - run: hub pr list
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: view the PR number
        run: |
          echo "PR number = ${{ github.event.pull_request.number }}"
          echo "PR number = ${{ env.PR_NUMBER }}"
